angular.module(
    'eu.crismaproject.pilotE.controllers',
    [
        'ngTable',
        'ui.bootstrap.alert',
        'eu.crismaproject.pilotE.services',
        'eu.crismaproject.pilotE.configuration'
    ]
);