angular.module(
    'eu.crismaproject.pilotE.directives',
    [
        'ui.select2',
        'ui.bootstrap.buttons',
        'ui.bootstrap.dropdownToggle',
        'ui.bootstrap.timepicker',
        'ui.bootstrap.tooltip',
        'ui.bootstrap.tpls'
    ]
);